@echo off
echo Starting CRM Application...
echo.
echo Checking for existing processes on port 3000...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :3000') do (
    echo Found process %%a on port 3000, stopping it...
    taskkill /F /PID %%a 2>nul
)
echo.
echo Starting development server...
npm start
